### ISSUE TITLE
All epubs are empty.

### ISSUE THREAD

**Issue by rafo** [NiklasGollenstede/epub-creator#1]
Nice Addon but right now all generated epubs are empty...

Firefox 62.0.3 (64-Bit)

**Comment by NiklasGollenstede** [comment]
Well, I just tried it booth with a website and a book from OverDrive, booth worked as expected.

Could you please provide a specific example (website / bublic sample from your library), or at least specify what you mean by "empty"?

**Comment by rafo** [comment]
Hi Niklas, thanx for your fast reply. The Books are only around 9kb and contain 2 empty sites.

Check this sites:

https://www.theatlantic.com/science/archive/2018/08/how-to-write-a-book-without-losing-your-mind/566462/

http://www.spiegel.de/wissenschaft/weltall/tandem-x-satellit-globales-3d-hoehenmodell-der-erde-veroeffentlicht-a-1232884.html

https://www.theatlantic.com/science/archive/2018/10/how-forests-affect-climate-change/572770/

https://www.theverge.com/2018/4/28/17293056/facebook-deletefacebook-social-network-monopoly

https://techcrunch.com/2018/10/13/what-to-expect-from-the-return-of-electric-scooters-in-sf/

I dient find a single one which works ...

Could you send me a link of a website which works? I don't have an Overdrive Account...

**Comment by NiklasGollenstede** [comment]
Hm. A file size of just a few kB isn't surprising. (Short) books without images are that small.

Extensions are not allowed to access the content of the reader mode pages, so this extension needs to parse everything itself. The included version of `Readability.js` was a bit outdated, causing minor differences between the reader page in Firefox and the downloaded content. Also, including cross-origin images didn't work.
In combination that meant that the downloaded books didn't contain any images, but other than that they were fine.

I've now addressed booth problems in the [latest beta](https://github.com/NiklasGollenstede/epub-creator#development-builds----).
If you are still only seeing blank pages, then that is a problem with your Firefox installation or your ePub reader. Which reader are you using? The last time I checked the produced books were (mostly) ePub 2.0 compliant and they always work in SumatraPDF.

**Comment by rafo** [comment]
> Hm. A file size of just a few kB isn't surprising. (Short) books without images are that small.

Yes I know. I tested this with different sites (Links on my last comment) and different epub plugins

> Extensions are not allowed to access the content of the reader mode pages, so this extension needs to parse everything itself.

I observed this from the other epub creates plugins also. Some of them work with the reader mode some not.

> In combination that meant that the downloaded books didn't contain any images, but other than that they were fine.

My books are completely empty. Same with the latest beta.

> If you are still only seeing blank pages, then that is a problem with your Firefox installation or your ePub reader.

Newest Firefox (no beta). All plugins deactivated.

> Which reader are you using?
iBook (MacOS) and EPUBReader plugin for Firefox. Every other Epub and every other EPUB generated from other Firefox-EPUB-Creation-Plugins works flawless.

**Comment by NiklasGollenstede** [comment]
Ok, found the problem. My workaround to access reader mode content added a `display: none` to the main page. SumatraPDF ignores such styles, your readers apparently don't. I created a new beta that fixes that and will upload it as the release version soon.
Thanks for telling me!

**Comment by rafo** [comment]
It works! Thank you so much!

**Comment by NiklasGollenstede** [comment]
Perfect! That was a silly mistake, but now it works even better than it was supposed to before.
I've just updated the release version as well.

**Comment by rafo** [comment]
I will promote this extension since it provides the best EPUBS of all Firefox Extensions. And I tested all of them ;D.

**Comment by NiklasGollenstede** [comment]
Thanks, I am glad it is of use to you ( now ;) )
