### ISSUE TITLE
Images are not linked properly when the url is not "clean"

### ISSUE THREAD

**Issue by dpshelio** [NiklasGollenstede/epub-creator#10]
For example, an [article from the guardian newspaper](https://www.theguardian.com/lifeandstyle/2021/jan/07/the-joys-of-being-an-absolute-beginner-for-life) shows right on the reader view but they don't show in different ebooks readers I tried.
Inspecting the created ebook shows they've been downloaded, however, there may be something wrong with the file names or that they don't have a "clear" extension.

i.e., the files are stored as: 
`2984.jpg?width=300&quality=45&auto=format&fit=max&dpr=2&s=268d9ccc054b66a94f0317ca4bf130ca`
but if they are renamed  to `2984.jpg` (and changed in the `content.opf` and `content.xhtml`) then it works fine.

Is that something that could be fixed on [loadResources](https://github.com/NiklasGollenstede/epub-creator/blob/49c97105a738ea579da2cdb87860e2a2ae5d7b80/common/epub.js#L113)?

**Comment by NiklasGollenstede** [comment]
Thanks for reporting. There was definitely something amiss here. Even though I am not sure whether the ePub files produced were strictly speaking correct or not, the readers I tried certainly also didn't like the query parameters in the file names.

The resources are being saved and referenced without the query parameters now. Loading these particular images (still?) fails in Chrome (based browsers), though. That's a more difficult issue, I think ...

But in Firefox it works. The beta build can be downloaded from GitHub now, and the main version on AMO was auto-approved (i.e. is available) as well.

---

And sorry for taking so long before looking at this. I had a rather important submission to finish.
