### ISSUE TITLE
"Cookies required"

### ISSUE THREAD

**Issue by alvarovm** [NiklasGollenstede/epub-creator#11]
Thanks for this effort. You gave new life old ereader.

I have issues converting epub from this ebook format
https://alephdigital.publica.la/reader/the-myth-of-piers-plowman

The epub produced has only the follow message:
"Cookies required"
"Cookies are not enabled in your browser. Some features may not work properly"

**Comment by NiklasGollenstede** [comment]
I am glad to hear that my work is of use to you!
In this case however, as already predicted by the prompt/warning, you will need to find some other way to get that page offline.

This extension works by essentially re-packaging the HTML content of a website as an ePub. That works well for content that is "plain" HTML to start with, and in some cases can work with HTML based books, depending on the reader (i.e. the webpage it's on).
What you linked to seems to be a PDF file (even if it does not let you download it as such).
Converting such a fixed page, very much representation focused document back into a content focused ePub, which allows for page reflows, is quite hard, and definitely outside the scope of this project. (There are some programs though that approximate PDF -> ePub conversion, with success depending on the specific PDF in question, which one obviously needs to have first).
