### ISSUE TITLE
descargar un libro completo

### ISSUE THREAD

**Issue by bichitoxxx** [NiklasGollenstede/epub-creator#13]
hay posibilidad de que descargue un libro completo y no solo la pagina que  este abierta?

**Comment by NiklasGollenstede** [comment]
"[Is it possible to download a complete book and not just the page that is open?](https://www.deepl.com/en/translator#es/en/hay%20posibilidad%20de%20que%20descargue%20un%20libro%20completo%20y%20no%20solo%20la%20pagina%20que%20este%20abierta%3F)"

---

See the readme:
> ePub creator [...] currently supports:
> * any web page that can be opened in Firefox's Reader Mode, which should work for most text-based websites
> * books opened in the online reader of the library service overdrive.com, which cooperates with many local libraries worldwide

So, unless it's an overdrive book, you will only get the currently open page.

I have thought about adding the capability to compose a book from multiple pages (#8), but that would take me at least two or three days, probably closer to a week, to do.

---

[Traducción realizada con la versión gratuita del traductor www.DeepL.com/Translator](https://www.deepl.com/en/translator#en/es/See%20the%20readme%3A%0A%0A%20%20%20%20ePub%20creator%20%5B...%5D%20currently%20supports%3A%0A%0A%20%20%20%20%20%20%20%20any%20web%20page%20that%20can%20be%20opened%20in%20Firefox's%20Reader%20Mode%2C%20which%20should%20work%20for%20most%20text-based%20websites%0A%20%20%20%20%20%20%20%20books%20opened%20in%20the%20online%20reader%20of%20the%20library%20service%20overdrive.com%2C%20which%20cooperates%20with%20many%20local%20libraries%20worldwide%0A%0ASo%2C%20unless%20it's%20an%20overdrive%20book%2C%20you%20will%20only%20get%20the%20currently%20open%20page.%0A%0AI%20have%20thought%20about%20adding%20the%20capability%20to%20compose%20a%20book%20from%20multiple%20pages%20(%238)%2C%20but%20that%20would%20take%20me%20at%20least%20two%20or%20three%20days%2C%20probably%20closer%20to%20a%20week%2C%20to%20do.):

Ver el readme:

>   El creador de ePub [...] soporta actualmente
> * cualquier página web que pueda abrirse en el Modo Lector de Firefox, lo que debería funcionar para la mayoría de los sitios web basados en texto
> *  libros abiertos en el lector online del servicio de biblioteca overdrive.com, que coopera con muchas bibliotecas locales de todo el mundo

Así que, a menos que sea un libro de Overdrive, sólo obtendrás la página abierta en ese momento.

He pensado en añadir la capacidad de componer un libro a partir de varias páginas (#8), pero eso me llevaría al menos dos o tres días, probablemente más cerca de una semana, para hacerlo.

**Comment by bichitoxxx** [comment]
perfecto, estare esperando el resultado
