### ISSUE TITLE
Unable to save images from medium

### ISSUE THREAD

**Issue by manujchandra** [NiklasGollenstede/epub-creator#6]
Hi, 

When I print preview this page:

https://towardsdatascience.com/machine-learning-kaggle-competition-part-one-getting-started-32fb9ff47426

I can see the images in the print preview. But when I save it as a epub, no images are saved. 

Please help. Thanks.

**Comment by NiklasGollenstede** [comment]
Hi you too!

Seems like you actually read the description, and this is indeed not covered there yet. I'll add something like this to the troubleshooting part:
> Note that some sites load e.g. images on demand, usually when scrolled to; before that, they won't be captured by the reader view or this extension.

Medium.com does lazy loading of images, by default it only loads a very low resolution placeholder. The full resolution image will only show in the reader view once you scrolled to that point of the page in the normal/full browser mode before. (And it also keeps the low res one -.-)

So, spam the page down key to get to the bottom of the page (just the `end` key does not always work) and then both the reader view and ePub Creator will work.
