### ISSUE TITLE
error when converting some pages

### ISSUE THREAD

**Issue by TomasEkeli** [NiklasGollenstede/epub-creator#9]
getting an error that says `global.crypto.subtle` is undefined on some pages

e.g. http://distributedweb.care/posts/who-owns-the-stars/

**Comment by NiklasGollenstede** [comment]
Apparently some cryptographic functions are not available on insecure pages, e.g. those without HTTPS 🔒. I never encountered that.

I wrote a fix that avoids using those (here non essential) functions when not available.
But Mozilla's extension signing times out, so I currently can't publish it 🙄

Alternative for now: use HTTPS (which the example page supports)

**Comment by NiklasGollenstede** [comment]
A couple attempts later, and the CI build works again. The update is in the [DEV channel](https://github.com/NiklasGollenstede/epub-creator#development-builds----) now.
